services:
  - type: web
    name: palpite-copa-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: PORT
        value: 3333

  - type: static
    name: palpite-copa-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    plan: free
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
